name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'  # Every day at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    # Required permissions for GitHub Pages deployment
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to latest version

    - name: Set up Python
      uses: actions/setup-python@v5  # Updated to latest version
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -e .

    - name: Generate HTML
      run: python -m github_showcase
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        cname: gh.showcase.vijaysingh.cloud
        publish_branch: gh-pages
        force_orphan: true
